blank_issues_enabled: true
contact_links:
  - name: âš¡ Feature Request
    url: https://github.com/computerrivet/qubt/discussions
    about: Please use GitHub Discussions for feature requests
  - name: ðŸ™‹ Question
    url: https://github.com/computerrivet/qubt/discussions
    about: Please use GitHub Discussions for questions about the theme
